apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    teir: frontend
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      teir: frontend
      project: expense
  template:
    metadata:
      labels:
        app: frontend
        teir: frontend
        project: expense
    spec:
      containers:
      - name: frontend
        image: parthureddy3/frontend:v1

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec: 
  type: LoadBalancer
  selector:   # lables are used as selectors 
    app: frontend
    teir: frontend
    project: expense
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 8080