apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    teir: database
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      teir: database
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        teir: database
        project: expense
    spec:
      containers:
      - name: mysql
        image: parthureddy3/mysql:v1

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec: 
  selector:   # lables are used as selectors 
    app: mysql
    teir: database
    project: expense
  ports:
    - protocol: TCP
      port: 3306 #service port
      targetPort: 3306